name: eventhub
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  image_picker: ^1.0.8
  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  email_validator: ^2.0.1  # Add this line
  intl: ^0.19.0
  firebase_core: ^2.31.0
  cloud_firestore: 4.15.8
  firebase_auth: ^4.17.8
  firebase_storage: ^11.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/profile/img/dp.png
    - lib/images/